### PR TITLE
Adds MongoDB Storage Adapter

### PR DESCRIPTION
**Pull request by securingsincity**
We've been using this on our production for a few months. It adds support for mongodb to be a source for the feature toggles.  

CC: @filipgolonka

### CODE REVIEW

**Comment by filipgolonka** [comment]
@securingsincity can you add following statement to .travis.yml file ? 
```
services:
  - mongodb
```

**Comment by wsromek** [comment]
👍

**Comment by ralfmaxxx** [comment]
👍

**Comment by securingsincity** [comment]
This should be all set now. I know a few people are looking for the functionality.

**Comment by arkadiuszmalina** [comment]
👍

**Comment by richardfullmer** [comment]
Awesome.  Thank you!

**Pull request merged**
