### PR TITLE
fix multiple user entries during addUser persistance

### PR DESCRIPTION
**Pull request by tonivdv**
The addUser checks if the user object is present in an array of string which
obviously always return false

### CODE REVIEW

**Comment by tonivdv** [comment]
@richardfullmer you think you can merge this soon, as this is a critical issue for us. Would not want to start using our fork.

Thanks

**Comment by richardfullmer** [comment]
Sorry for the delay.  Thanks again!

**Comment by tonivdv** [comment]
@richardfullmer possible this repo is not auto updating packagist? Cause the tag 2.1.1 with this fix is not yet on packagist. Or am I missing something?

**Comment by richardfullmer** [comment]
Manually updated on packagist... haven't had to do that before.  Maybe their jobs are behind or something.  It's there now.

**Pull request merged**
